{% set native = 'm2w64-' if win else '' %}

package:
  name: alinea.pyratp
  version: 2.0.1

source:
    path: ..

requirements:
    host:
        - python x.x
        - setuptools <60.0
        - numpy x.x
    build:
        - python {{PY_VER}}
        - numpy
        - meson # Maybe deprecated for current version
        - make
        - compilers
        - m2w64-toolchain   # [win]
        - charset-normalizer
    run:
        - python x.x
        - path.py
        - libgfortran 
        - numpy
        - scipy
        - pandas
        #- openalea.mtg
        #- openalea.visualea
test:
    imports:
        - alinea.pyratp
        - alinea.pyratp.pyratp
about:
    home: http://github.com/openalea-incubator/PyRATP
    license: Cecill-C
    summary: RATP is a model to compute Radiation Absorption, Transpiration and Photosynthesis.
extra:
    recipe-maintainers:
        - pradal
